### ISSUE TITLE
mysql启动失败，可以帮助看看是什么问题吗?

### ISSUE THREAD

**Issue by BFlabourer** [beautysoft/docker-lnmp#5]
mysqld: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied

**Comment by cuiziwei** [comment]
没有权限，给 /work/components/mysql 777 权限重试

**Comment by cuiziwei** [comment]
@BFlabourer 没有权限，给 /work/components/mysql 777 权限重试

**Comment by BFlabourer** [comment]
@cuiziwei 
root用户以及非root用户，mysql启动都会报以下错误:
mysqld: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied
1、/lib/x86_64-linux-gnu/libpthread.so.0
     /lib/i386-linux-gnu/libpthread.so.0
    /var/lib/docker/aufs/diff
   我将上面的目录加了777权限，但是依然报错
2、是否跟我本地安装了mysql有关？
3、如果是，该怎么做呢？
对以上问题，是否可以帮助解答一下，感谢

**Comment by cuiziwei** [comment]
@BFlabourer 加我微信 cuiziwei
