### ISSUE TITLE
Build的时候报 Some index files failed to download.错误

### ISSUE THREAD

**Issue by WxYoung** [beautysoft/docker-lnmp#7]
Get:27 http://mirrors.163.com jessie/non-free amd64 Packages [101 kB]
Get:28 http://mirrors.163.com jessie/contrib amd64 Packages [59.2 kB]
Get:29 http://mirrors.163.com jessie/main amd64 Packages [9063 kB]
Fetched 22.4 MB in 26s (850 kB/s)
W: Failed to fetch http://mirrors.163.com/debian/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php71' failed to build: The command '/bin/sh -c apt-get -o Acquire::Check-Valid-Until=false update && apt-get -y upgrade' returned a non-zero code: 100

**Comment by WxYoung** [comment]
已经解决，换成aliyun的源就好了

**Comment by cuiziwei** [comment]
@WxYoung 赞
